package com.example.trynavigation.ui.repozitory

import com.example.trynavigation.ui.data.FirstModel

class FirstRepozitory {
        private var textList = mutableListOf<FirstModel>()

    fun getListOfText(): MutableList<FirstModel> {
        textList.add(FirstModel("https://http.cat/100", "Continue"))
        textList.add(FirstModel("https://http.cat/101", "Switching Protocols"))
        textList.add(FirstModel("https://http.cat/102", "Processing"))
        textList.add(FirstModel("https://http.cat/103", "Early Hints"))
        textList.add(FirstModel("https://http.cat/200", "OK"))
        textList.add(FirstModel("https://http.cat/201", "Created"))
        textList.add(FirstModel("https://http.cat/202", "Accepted"))
        textList.add(FirstModel("https://http.cat/203", "Non-Authoritative Information"))
        textList.add(FirstModel("https://http.cat/204", "No Content"))
        textList.add(FirstModel("https://http.cat/206", "Partial Content"))
        textList.add(FirstModel("https://http.cat/207", "Multi-Status"))
        textList.add(FirstModel("https://http.cat/300", "Multiple Choices"))
        textList.add(FirstModel("https://http.cat/301", "Moved Permanently"))
        textList.add(FirstModel("https://http.cat/302", "Found"))
        textList.add(FirstModel("https://http.cat/303", "See Other"))
        textList.add(FirstModel("https://http.cat/304", "Not Modified"))
        textList.add(FirstModel("https://http.cat/305", "Use Proxy"))
        textList.add(FirstModel("https://http.cat/307", "Temporary Redirect"))
        textList.add(FirstModel("https://http.cat/308", "Permanent Redirect"))
        textList.add(FirstModel("https://http.cat/400", "Bad Request"))
        textList.add(FirstModel("https://http.cat/401", "Unauthorized"))
        textList.add(FirstModel("https://http.cat/402", "Payment Required"))
        textList.add(FirstModel("https://http.cat/403", "Forbidden"))
        textList.add(FirstModel("https://http.cat/404", "Not Found"))
        textList.add(FirstModel("https://http.cat/405", "Method Not Allowed"))
        textList.add(FirstModel("https://http.cat/406", "Not Acceptable"))
        textList.add(FirstModel("https://http.cat/407", "Proxy Authentication Required"))
        textList.add(FirstModel("https://http.cat/408", "Request Timeout"))
        textList.add(FirstModel("https://http.cat/409", "Conflict"))
        textList.add(FirstModel("https://http.cat/410", "Gone"))
        textList.add(FirstModel("https://http.cat/411", "Length Required"))
        textList.add(FirstModel("https://http.cat/412", "Precondition Failed"))
        textList.add(FirstModel("https://http.cat/413", "Payload Too Large"))
        textList.add(FirstModel("https://http.cat/414", "Request-URI Too Long"))
        textList.add(FirstModel("https://http.cat/415", "Unsupported Media Type"))
        textList.add(FirstModel("https://http.cat/416", "Request Range Satisfiable"))
        textList.add(FirstModel("https://http.cat/417", "Expectation Failed"))
        textList.add(FirstModel("https://http.cat/418", "I'm a teapot"))
        textList.add(FirstModel("https://http.cat/420", "Enhance Your Calm"))
        textList.add(FirstModel("https://http.cat/421", "Misdirected Request"))
        textList.add(FirstModel("https://http.cat/422", "Unprocessable Entity"))
        textList.add(FirstModel("https://http.cat/423", "Locked"))
        textList.add(FirstModel("https://http.cat/424", "Failed Dependency"))
        textList.add(FirstModel("https://http.cat/425", "Too Early"))
        textList.add(FirstModel("https://http.cat/426", "Upgrade Requested"))
        textList.add(FirstModel("https://http.cat/429", "Too Many Requested"))
        textList.add(FirstModel("https://http.cat/431", "Request Header Fields Too Large"))
        textList.add(FirstModel("https://http.cat/444", "No Response"))
        textList.add(FirstModel("https://http.cat/450", "Blocked Windows Parental Controls"))
        textList.add(FirstModel("https://http.cat/451", "Unavailable For Legal Reasons"))
        textList.add(FirstModel("https://http.cat/497", "HTTP Request Sent HTTPS Port"))
        textList.add(FirstModel("https://http.cat/498", "Token expired/invalid"))

        return textList

    }
}